// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_level_xviii = "CgkI95HWzekaEAIQHg"; // <GPGSID>
        public const string achievement_the_fastest = "CgkI95HWzekaEAIQCw"; // <GPGSID>
        public const string achievement_level_i = "CgkI95HWzekaEAIQDQ"; // <GPGSID>
        public const string achievement_a_light_in_the_dark = "CgkI95HWzekaEAIQIQ"; // <GPGSID>
        public const string achievement_level_xiv = "CgkI95HWzekaEAIQGg"; // <GPGSID>
        public const string achievement_the_best_of_the_classic = "CgkI95HWzekaEAIQCg"; // <GPGSID>
        public const string achievement_level_viii = "CgkI95HWzekaEAIQFA"; // <GPGSID>
        public const string achievement_level_xv = "CgkI95HWzekaEAIQGw"; // <GPGSID>
        public const string achievement_a_simple_maze = "CgkI95HWzekaEAIQBg"; // <GPGSID>
        public const string achievement_level_xix = "CgkI95HWzekaEAIQHw"; // <GPGSID>
        public const string achievement_level_iii = "CgkI95HWzekaEAIQDw"; // <GPGSID>
        public const string achievement_level_iv = "CgkI95HWzekaEAIQEA"; // <GPGSID>
        public const string achievement_level_vi = "CgkI95HWzekaEAIQEg"; // <GPGSID>
        public const string achievement_a_really_big_maze = "CgkI95HWzekaEAIQCQ"; // <GPGSID>
        public const string achievement_level_xi = "CgkI95HWzekaEAIQFw"; // <GPGSID>
        public const string achievement_a_little_big_maze = "CgkI95HWzekaEAIQBw"; // <GPGSID>
        public const string achievement_level_xiii = "CgkI95HWzekaEAIQGQ"; // <GPGSID>
        public const string achievement_a_big_maze = "CgkI95HWzekaEAIQCA"; // <GPGSID>
        public const string achievement_the_last_hundredth_of_a_second = "CgkI95HWzekaEAIQDA"; // <GPGSID>
        public const string achievement_level_xx = "CgkI95HWzekaEAIQIA"; // <GPGSID>
        public const string achievement_level_v = "CgkI95HWzekaEAIQEQ"; // <GPGSID>
        public const string achievement_level_ii = "CgkI95HWzekaEAIQDg"; // <GPGSID>
        public const string achievement_level_xvi = "CgkI95HWzekaEAIQHA"; // <GPGSID>
        public const string achievement_level_xvii = "CgkI95HWzekaEAIQHQ"; // <GPGSID>
        public const string achievement_level_x = "CgkI95HWzekaEAIQFg"; // <GPGSID>
        public const string achievement_level_xii = "CgkI95HWzekaEAIQGA"; // <GPGSID>
        public const string leaderboard_top_score_by_maze = "CgkI95HWzekaEAIQAg"; // <GPGSID>
        public const string achievement_level_vii = "CgkI95HWzekaEAIQEw"; // <GPGSID>
        public const string achievement_level_ix = "CgkI95HWzekaEAIQFQ"; // <GPGSID>

}

